name: Build and deploy ASP.NET app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    # - name: Restore NuGet packages
    #   run: nuget restore

    - name: Build the application
      run: msbuild /p:Configuration=Release /t:build

    # - name: Publish the application
    #   run:  msbuild /p:Configuration=Release /t:publish
    - name: Publish the application
      run: msbuild WebApplication/WebApplication.csproj /p:Configuration=Release /t:publish /p:PublishDir=website

    
    - name: List files in output directory
      run: |
        cd ./WebApplication/bin/Release/net5.0
        ls -R ${github.workspace}

    - name: Upload the application artifacts
      uses: actions/upload-artifact@v2
      with:
        name: published_web
        path: ./WebApplication/bin/Release/net5.0/publish
        if-no-files-found: fail
 
#     - name: Check if files exist
#       if: "test -n '$(find ./bin/Release/net5.0/publish -type f -print -quit)'"
#       run: echo "Files exist in path"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'EmployeeProject29'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ github.workspace }}/bin/Release/net5.0/publish
        slot-name: 'production'
        resource-group: 'MyRgrp'
        action: 'swap'
        timeout: '3600'
